version: "3"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile_Spark
    image: spark-demo:latest
    ports:
      - "8080:8080"
      - "7077:7077"
  slave_1:
    image: spark-demo:latest
    entrypoint: /apps/spark_demo/spark/sbin/start-slave.sh -c 1 -m 512M spark://master:7077
    depends_on:
      - master
  slave_2:
    image: spark-demo:latest
    entrypoint: /apps/spark_demo/spark/sbin/start-slave.sh -c 1 -m 512M spark://master:7077
    depends_on:
      - master
  war:
    build:
      context: .
      dockerfile: Dockerfile
    image: spark-demo-war:latest
    ports:
      - "8081:8080"
    depends_on:
      - master